version: "3"
services:
  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - ./mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    restart: always
  web:
    image: tomcat
    container_name: web
    depend_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./tomcat:/usr/local/tomcat
    restart: always
