#! /bin/bash

. <(grep DBPSWD .env)
MYSQL='docker-compose exec -T -- db mysql -uroot --password='"$DBPSWD"' --default-character-set=utf8mb4'

#cd $(dirname $(realpath ${BASH_SOURCE[0]}))
cat << EOF | $MYSQL
$*
EOF
