version: "3"
services:
  nifi:
    image: apache/nifi:1.18.0
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
#      - SINGLE_USER_CREDENTIALS_USERNAME=admin
#      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    ports:
      - 8443:8443
